### PR TITLE
Update to work with mesos 0.28.1

### PR DESCRIPTION
**Pull request by rick**
Taking a stab at getting this working.  So far I can only do this on ruby versions < 2.2 due to changes in ruby internals regarding threading functions.

### CODE REVIEW

**Comment by rick** [comment]
At this point, this builds successfully under ruby-2.1.9. In the hidden tea leaves there are deprecation warnings about ruby threading functions which change(d) in 2.2.*.

**Comment by rick** [comment]
Linking to my ongoing build notes here: https://gist.github.com/rick/78813af85378f258b989a0c508578051

**Comment by rick** [comment]
Currently segfaults when running `examples/test_framework.rb` under ruby 2.1.9. Backtrace, etc., here: https://gist.github.com/rick/be1b3476ca5c8d9a023c90cbc542395f

**Comment by rick** [comment]
cc @burke on the random off-chance there's any wisdom from days of yore that rings a bell.

**Comment by burke** [comment]
hah, exectutor. Don't remember much of this code really, but seems like the right path.

**Comment by rick** [comment]
Not going to pursue this direction, so, letting this go.  Cheers.

:rocket: :boom:

**Pull request closed without merging**
